[project]
name = "Heart-Attack-Predictor"
version = "1.0"
description = "Heart attack risk predictor using machine learning"
authors = [
    {name = "Akila Prabath", email = "akilaprabath861@gmail.com"}
]
requires-python = ">=3.11"
